### ISSUE TITLE
Segfault when checking for overlap in atom groups with malformed config

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#253]
Here is an input:
```
colvar {
    name a
    coordnum {
      group1 {
            atomNumbers 4 5 6

      group2 {   
            atomNumbers 7 8 9
            }
        }
    }
}
```

The log:
```
colvars:           Atom group "group1" defined with 3 atoms requested: total mass = 25.03, total charge = 0.
colvars: Error: keyword "group2" is not supported, or not recognized in this context.
colvars: Error parsing definition for atom group "group1"
colvars: .
colvars: Error: definition for atom group "group2" not found.

Thread 1 "vmd_LINUXAMD64" received signal SIGSEGV, Segmentation fault.
```

and the backtrace:
```
#0  0x00005555556a55d3 in colvarmodule::atom_group::overlap(colvarmodule::atom_group const&, colvarmodule::atom_group const&) ()
#1  0x00005555557497ba in colvar::coordnum::coordnum(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#2  0x000055555572a7eb in int colvar::init_components_type<colvar::coordnum>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*) ()
#3  0x000055555571b6f6 in colvar::init_components(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x000055555571f127 in colvar::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x0000555555780f4e in colvarmodule::parse_colvars(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x00005555557860fe in colvarmodule::parse_config(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#7  0x0000555555786591 in colvarmodule::read_config_file(char const*) ()
```

**Comment by jhenin** [comment]
Update: the same happens when group2 is missing entirely. Should be easy to fix.
